#!/bin/bash

ln -sf $PWD/config.bash $HOME/.bash_aliases
ls -l $HOME/.bash_aliases

ln -sf $PWD/vimrc $HOME/.vimrc
ls -l $HOME/.vimrc

ln -sf $PWD/tmux.conf $HOME/.tmux.conf
ls -l $HOME/.tmux.conf

ln -sf $PWD/lynxrc $HOME/.lynxrc
ls -l $HOME/.lynxrc

ln -sf $PWD/lynx.lss /etc/lynx/lynx.lss
ls -l /etc/lynx/lynx.lss


